apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: spring-demo

  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/Amy525-g/devsecops-pipeline.git
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true